name: BMI Calculator Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  start_server_and_run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  

    - name: install chrome
      uses: browser-actions/setup-chrome@v1

    - name: install driver
      run: apt install -y mesa-vulkan-drivers vulkan-utils
      
      
    - name: Install dependencies
      run: npm install

    - name: Start server
      run: npm start &

    - name: Wait for server to be up
      run: sleep 10

    - name: Install Cypress
      run: npm install cypress --save-dev  

    - name: Run Cypress Test
      uses: cypress-io/github-action@v4
      with:
        command: npm run cypress:open
        browser: chrome

    - name: Run Cypress headless
      run:  npx cypress run --headless

      





